<?php

// var_dump($result);
if ($result->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <td colspan="1"><?php echo $this->tag->linkTo(["/", "Back", 'class' => 'btn btn-danger']); ?></td>
                <td colspan="2">Results quantity: <?php echo $result->count(); ?></td>
            </tr>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Like</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Results quantity: <?php echo $result->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($result as $data) { ?>
                <tr>
                    <td><?php echo $data->ID; ?></td>
                    <td><?php echo $data->hostel_name; ?></td>
                    <td><?php echo $data->like; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php
}
